# Copyright 2022 MobiledgeX, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaultcerts.stable.mobiledgex.net
spec:
  group: stable.mobiledgex.net
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [domain, secretName]
              properties:
                domain:
                  type: array
                  items:
                    type: string
                secretName:
                  type: string
  conversion:
    strategy: None

  scope: Namespaced
  names:
    plural: vaultcerts
    singular: vaultcert
    kind: VaultCert
    shortNames:
    - vc
