---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-operator
  namespace: vault-cert
  labels:
    operator: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      operator: shell-operator
  template:
    metadata:
      name: shell-operator
      labels:
        operator: shell-operator
    spec:
      containers:
      - name: shell-operator
        image: venkytv/shell-operator:vault-cert
        imagePullPolicy: Always
        env:
        - name: VAULT_ADDR
          value: https://example.com
        - name: VAULT_ROLE_ID
          value: foo
        - name: VAULT_SECRET_ID
          value: bar
      serviceAccountName: crd-vaultcert-acc
