---
apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
  namespace: vault-cert
spec:
  containers:
  - name: shell-operator
    image: venkytv/shell-operator:vault-cert
    imagePullPolicy: Always
  serviceAccountName: crd-vaultcert-acc
